# Generated by Django 2.2.2 on 2021-02-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210216_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
    ]
