# Generated by Django 2.2.2 on 2021-02-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210216_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_address',
            new_name='client_location',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
