# Generated by Django 2.2.2 on 2021-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210217_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
