# Generated by Django 2.2.2 on 2021-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Confirmpassword',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
